/*
  Warnings:

  - The values [TECHNOLOGY,HEALTH,EDUCATION,ENVIRONMENT,LAW,ARTS,ENGINEERING,SOCIAL] on the enum `ProjectArea` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ProjectArea_new" AS ENUM ('CONTROLE_SISTEMAS', 'SISTEMAS_MECATRONICOS', 'ACIONAMENTOS_ELETRICOS', 'SISTEMAS_INTELIGENTES', 'ROBOTICA_INDUSTRIAL', 'AUTOMACAO_MECANICA', 'AUTOMACAO_ELETRICA', 'ENGENHARIA_PROJETO', 'MANUFATURA_DIGITAL', 'PROJETO_COMPUTADOR', 'SIMULACAO_COMPUTACIONAL');
ALTER TABLE "Project" ALTER COLUMN "area" DROP DEFAULT;
ALTER TABLE "Project" ALTER COLUMN "area" TYPE "ProjectArea_new" USING ("area"::text::"ProjectArea_new");
ALTER TYPE "ProjectArea" RENAME TO "ProjectArea_old";
ALTER TYPE "ProjectArea_new" RENAME TO "ProjectArea";
DROP TYPE "ProjectArea_old";
ALTER TABLE "Project" ALTER COLUMN "area" SET DEFAULT 'CONTROLE_SISTEMAS';
COMMIT;

-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "area" SET DEFAULT 'CONTROLE_SISTEMAS';
